(ns ldf.dev
  "This namespace is intended to help the development process.
   Load it, and the qualified keywords defined here will be
   available for autocompletion in your editor and REPL.")

(def terms

  {

   ;; http://www.w3.org/2000/01/rdf-schema#
   :rdfs
   #{:rdfs/Resource
     :rdfs/Class
     :rdfs/subClassOf
     :rdfs/subPropertyOf
     :rdfs/comment
     :rdfs/label
     :rdfs/domain
     :rdfs/range
     :rdfs/seeAlso
     :rdfs/isDefinedBy
     :rdfs/Literal
     :rdfs/Container
     :rdfs/ContainerMembershipProperty
     :rdfs/member
     :rdfs/Datatype}

   ;; http://www.w3.org/1999/02/22-rdf-syntax-ns#
   :rdf
   #{:rdf/HTML
     :rdf/langString
     :rdf/PlainLiteral
     :rdf/type
     :rdf/Property
     :rdf/Statement
     :rdf/statement
     :rdf/subject
     :rdf/predicate
     :rdf/object
     :rdf/Bag
     :rdf/Seq
     :rdf/Alt
     :rdf/List
     :rdf/nil
     :rdf/first
     :rdf/rest
     :rdf/XMLLiteral}

   ;; http://www.w3.org/ns/ldp#
   :ldp
   #{:ldp/Resource
     :ldp/RDFSource
     :ldp/NonRDFSource
     :ldp/Container
     :ldp/BasicContainer
     :ldp/DirectContainer
     :ldp/IndirectContainer
     :ldp/hasMemberRelation
     :ldp/isMemberOfRelation
     :ldp/membershipResource
     :ldp/insertedContentRelation
     :ldp/member
     :ldp/contains
     :ldp/MemberSubject
     :ldp/PreferContainment
     :ldp/PreferMembership
     :ldp/PreferEmptyContainer
     :ldp/PreferMinimalContainer
     :ldp/constrainedBy
     :ldp/pageSortCriteria
     :ldp/PageSortCriterion
     :ldp/pageSortPredicate
     :ldp/pageSortOrder
     :ldp/pageSortCollation
     :ldp/Ascending
     :ldp/Descending
     :ldp/Page
     :ldp/pageSequence
     :ldp/inbox}

   ;; http://www.w3.org/2002/07/owl#
   :owl
   #{:owl/AllDifferent
     :owl/AllDisjointClasses
     :owl/AllDisjointProperties
     :owl/Annotation
     :owl/AnnotationProperty
     :owl/AsymmetricProperty
     :owl/Axiom
     :owl/Class
     :owl/DataRange
     :owl/DatatypeProperty
     :owl/DeprecatedClass
     :owl/DeprecatedProperty
     :owl/FunctionalProperty
     :owl/InverseFunctionalProperty
     :owl/IrreflexiveProperty
     :owl/NamedIndividual
     :owl/NegativePropertyAssertion
     :owl/Nothing
     :owl/ObjectProperty
     :owl/Ontology
     :owl/OntologyProperty
     :owl/ReflexiveProperty
     :owl/Restriction
     :owl/SymmetricProperty
     :owl/TransitiveProperty
     :owl/Thing
     :owl/allValuesFrom
     :owl/annotatedProperty
     :owl/annotatedSource
     :owl/annotatedTarget
     :owl/assertionProperty
     :owl/backwardCompatibleWith
     :owl/bottomDataProperty
     :owl/bottomObjectProperty
     :owl/cardinality
     :owl/complementOf
     :owl/datatypeComplementOf
     :owl/deprecated
     :owl/differentFrom
     :owl/disjointUnionOf
     :owl/disjointWith
     :owl/distinctMembers
     :owl/equivalentClass
     :owl/equivalentProperty
     :owl/hasKey
     :owl/hasSelf
     :owl/hasValue
     :owl/imports
     :owl/incompatibleWith
     :owl/intersectionOf
     :owl/inverseOf
     :owl/maxCardinality
     :owl/maxQualifiedCardinality
     :owl/members
     :owl/minCardinality
     :owl/minQualifiedCardinality
     :owl/onClass
     :owl/onDataRange
     :owl/onDatatype
     :owl/oneOf
     :owl/onProperties
     :owl/onProperty
     :owl/priorVersion
     :owl/propertyChainAxiom
     :owl/propertyDisjointWith
     :owl/qualifiedCardinality
     :owl/sameAs
     :owl/someValuesFrom
     :owl/sourceIndividual
     :owl/targetIndividual
     :owl/targetValue
     :owl/topDataProperty
     :owl/topObjectProperty
     :owl/unionOf
     :owl/versionInfo
     :owl/versionIRI
     :owl/withRestrictions}

   ;; http://xmlns.com/foaf/0.1/
   :foaf
   #{:foaf/Agent
     :foaf/Document
     :foaf/Group
     :foaf/Image
     :foaf/LabelProperty
     :foaf/OnlineAccount
     :foaf/OnlineChatAccount
     :foaf/OnlineEcommerceAccount
     :foaf/OnlineGamingAccount
     :foaf/Organization
     :foaf/Person
     :foaf/PersonalProfileDocument
     :foaf/Project
     :foaf/account
     :foaf/accountName
     :foaf/accountServiceHomepage
     :foaf/age
     :foaf/based_near
     :foaf/birthday
     :foaf/currentProject
     :foaf/depiction
     :foaf/depicts
     :foaf/dnaChecksum
     :foaf/familyName
     :foaf/family_name
     :foaf/firstName
     :foaf/focus
     :foaf/fundedBy
     :foaf/geekcode
     :foaf/gender
     :foaf/givenName
     :foaf/givenname
     :foaf/holdsAccount
     :foaf/homepage
     :foaf/img
     :foaf/interest
     :foaf/isPrimaryTopicOf
     :foaf/knows
     :foaf/lastName
     :foaf/logo
     :foaf/made
     :foaf/maker
     :foaf/mbox
     :foaf/mbox_sha1sum
     :foaf/member
     :foaf/membershipClass
     :foaf/myersBriggs
     :foaf/name
     :foaf/nick
     :foaf/openid
     :foaf/page
     :foaf/pastProject
     :foaf/phone
     :foaf/plan
     :foaf/primaryTopic
     :foaf/publications
     :foaf/schoolHomepage
     :foaf/sha1
     :foaf/skypeID
     :foaf/status
     :foaf/surname
     :foaf/theme
     :foaf/thumbnail
     :foaf/tipjar
     :foaf/title
     :foaf/topic
     :foaf/topic_interest
     :foaf/weblog
     :foaf/workInfoHomepage
     :foaf/workplaceHomepage}

   ;; http://www.w3.org/ns/solid/terms#
   :solid
   #{:solid/Account
     :solid/Inbox
     :solid/ListedDocument
     :solid/Notification
     :solid/Patch
     :solid/Timeline
     :solid/TypeIndex
     :solid/TypeRegistration
     :solid/UnlistedDocument
     :solid/account
     :solid/deletes
     :solid/forClass
     :solid/inbox
     :solid/inserts
     :solid/instance
     :solid/instanceContainer
     :solid/loginEndpoint
     :solid/logoutEndpoint
     :solid/notification
     :solid/privateTypeIndex
     :solid/publicTypeIndex
     :solid/read
     :solid/typeIndex
     :solid/oidcIssuer
     :solid/patches
     :solid/timeline
     :solid/where
     :solid/storageQuota
     :solid/storageUsage}

   })
